jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from django.conf import settings
from django.conf.urls.static import static

schema_view = get_schema_view(
   openapi.Info(
      title="Jobs Portal API",
      default_version='v1',
      description="Jobs Portal Api Description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobsapp.urls')),
    path('', include('accounts.urls')),
    path('api/', include([
        path('swagger', schema_view.with_ui('swagger', cache_timeout=0)),
        path('', include('accounts.api.urls')),
        path('', include('jobsapp.api.urls')),
    ])),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobsapp/urls.py
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from .views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = "jobs"

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('search', SearchView.as_view(), name='searh'),
    path('employer/dashboard/', include([
        path('', DashboardView.as_view(), name='employer-dashboard'),
        path('all-applicants', ApplicantsListView.as_view(), name='employer-all-applicants'),
        path('applicants/<int:job_id>', ApplicantPerJobView.as_view(), name='employer-dashboard-applicants'),
        path('mark-filled/<int:job_id>', filled, name='job-mark-filled'),
    ])),
    path('apply-job/<int:job_id>', ApplyJobView.as_view(), name='apply-job'),
    path('jobs', JobListView.as_view(), name='jobs'),
    path('jobs/<int:id>', JobDetailsView.as_view(), name='jobs-detail'),

    path('cvinfo', employee.cvinfo, name='cvinfo'),
    path('cv_save', employee.cv_save, name='cv_save'),

    path('eduinfo', employee.eduinfo, name='eduinfo'),
    path('education/save', employee.education_save, name='edu_save'),

    path('employee/cv/view/pdf', PDF.as_view(), name='pdf'),
    #path('employer/jobs/create', JobCreateView.as_view(), name='employer-jobs-create'),
    #path('employer/jobs/create', employer.job_post, name='employer-jobs-create'),
    path('employer/jobs/create', job_post.as_view(), name='employer-jobs-create'),
    #path('employee/cvinfo', cvinfo.as_view(), name='cvinfo'),
    #path('employee/cv/view', view_cv.as_view(), name='employee-view-cv'),
    path('employee/cv/view', employee.view_cv, name='employee-view-cv'),
    path('job/details/update/<int:pk>', EditJobView.as_view(), name='job-details-update'),
    path('job/details/delete/<int:pk>', DeleteJobView.as_view(), name='job-details-delete'),
    #path('job/employee/details/<int:pk>', EmployeeDetailsView.as_view(), name='employee-details'),
    path('job/employee/details/<int:pk>', employer.EmployeeDetailsView, name='employee-details'),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobsapp/api/views/employer.py
from rest_framework.generics import ListAPIView
from rest_framework.permissions import IsAuthenticated

from jobsapp.api.permissions import IsEmployer
from jobsapp.api.serializers import ApplicantSerializer
from jobsapp.models import Applicant


class ApplicantsListAPIView(ListAPIView):
    serializer_class = ApplicantSerializer
    permission_classes = [IsAuthenticated, IsEmployer]

    def get_queryset(self):
        user = self.request.user
        return Applicant.objects.filter(job__user_id=user.id)

jobsapp/views/employer.py
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView,UpdateView,DeleteView
from jobsapp import urls

from jobsapp.decorators import user_is_employer
from jobsapp.forms import CreateJobForm,JobForm, JobUpdateForm
from jobsapp.models import Job, Applicant , JobModel,CvModel,Education
from jobsapp import models

from django.shortcuts import render
from django.views import View



class DashboardView(ListView):
    #model = Job
    model = JobModel
    template_name = 'jobs/employer/dashboard.html'
    context_object_name = 'jobs'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user_id=self.request.user.id)


class ApplicantPerJobView(ListView):
    model = Applicant
    template_name = 'jobs/employer/applicants.html'
    context_object_name = 'applicants'
    paginate_by = 1

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get_queryset(self):
        return Applicant.objects.filter(job_id=self.kwargs['job_id']).order_by('id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['job'] = JobModel.objects.get(id=self.kwargs['job_id'])
        return context


class JobCreateView(CreateView):
    template_name = 'jobs/create.html'
    form_class = CreateJobForm
    success_url = reverse_lazy('jobs:employer-dashboard')
    extra_context = {
        'title': 'Post New Job'
    }

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return reverse_lazy('accounts:login')
        if self.request.user.is_authenticated and self.request.user.role != 'employer':
            return reverse_lazy('accounts:login')
        return super().dispatch(self.request, *args, **kwargs)

    '''def form_valid(self, form):
        form.instance.user = self.request.user
        #return super(JobCreateView, self).form_valid(form)
        job = form.save(commit=False)
        job.save()
        return HttpResponseRedirect(reverse_lazy('jobs:employer-dashboard'))'''

    def post(self, request, *args, **kwargs):
        self.object = None
        #form = self.get_form(self.form_class)
        #form = self.form_class
        form = CreateJobForm(request.POST or None)
        if form.is_valid():
            form.instance.user = self.request.user
            instance = form.save()
            instance.save()
            #job = form.save(commit=False)
            #form.save()
            return HttpResponseRedirect(reverse_lazy('jobs:employer-dashboard'))
            #return redirect('accounts:login')
            #return self.form_valid(form)
        else:
            return self.form_invalid(form)


class ApplicantsListView(ListView):
    model = Applicant
    template_name = 'jobs/employer/all-applicants.html'
    context_object_name = 'applicants'

    def get_queryset(self):
        # jobs = Job.objects.filter(user_id=self.request.user.id)
        return self.model.objects.filter(job__user_id=self.request.user.id)

'''class EmployeeDetailsView(ListView):
    model = CvModel
    template_name = 'jobs/viewcv.html'
    context_object_name = 'cv'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)
    def get_queryset(self):
        # jobs = Job.objects.filter(user_id=self.request.user.id)
        return self.model.objects.filter(user_id= self.kwargs['pk'])'''
def EmployeeDetailsView(request,pk):
    cv = CvModel.objects.filter(user_id= pk)
    edu = Education.objects.filter(user_id= pk)
    return render(request,"jobs/viewcv.html",{"cv": cv,"edu":edu})


@login_required(login_url=reverse_lazy('accounts:login'))
def filled(request, job_id=None):
    try:
        job = JobModel.objects.get(user_id=request.user.id, id=job_id)
        job.filled = True
        job.save()
    except IntegrityError as e:
        print(e.message)
        return HttpResponseRedirect(reverse_lazy('jobs:employer-dashboard'))
    return HttpResponseRedirect(reverse_lazy('jobs:employer-dashboard'))


class job_post(View):
    form_class = JobForm
    template_name = 'jobs/job_create.html'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def get(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        context = {'form': form, }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            form.instance.user = self.request.user
            instance = form.save()
            instance.save()
            return HttpResponseRedirect(reverse_lazy('jobs:employer-dashboard'))

        return render(request, self.template_name, {'form': form})

'''class EditJobView(View):
    model = JobModel
    form_class = JobUpdateForm
    #context_object_name = 'form'
    template_name = 'jobs/employer/edit-profile.html'

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def get(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        context = {'form': form, }
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST or None)
        if form.is_valid():
            form.instance.user = self.request.user
            instance = form.save()
            instance.save()
            return HttpResponseRedirect(reverse_lazy('jobs:employer-dashboard'))

        return render(request, self.template_name, {'form': form})'''


class EditJobView(UpdateView):
    model = JobModel
    template_name = 'jobs/employer/edit-profile.html'
    #fields = ['title','description','location','type','category','salary','company_name','company_description']
    #fields = '__all__'
    fields = ['title', 'description','company_description','location','salary','last_date']
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('jobs:employer-dashboard')


class DeleteJobView(DeleteView):
    model = JobModel
    template_name = 'jobs/employer/delete_job.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('jobs:employer-dashboard')


'''class EditJobView(UpdateView):
    model = JobModel
    form_class = JobUpdateForm
    #context_object_name = 'form'
    template_name = 'jobs/employer/edit-profile.html'
    success_url = reverse_lazy('jobs:employer-dashboard')
    @method_decorator(login_required(login_url=reverse_lazy('accounts:login')))
    @method_decorator(user_is_employer)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(self.request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
        except Http404:
            raise Http404("User doesn't exists")
        #form = JobModel.objects.get(id=self.kwargs['self.request.id'])
        #print (form)
        return render(request, self.template_name, {'form': form})
        #context = self.get_context_data(object=self.object)
        #return self.render_to_response(self.get_context_data())


    def get_object(self, queryset=None):
        obj = self.request.user

        print('entered to get_object')
        if obj is None:
            raise Http404("Job doesn't exists")
        return obj'''

'''@login_required
def job_post(request):
    #print (request.user.id)
    template_name = 'jobs/job_create.html'
    form = JobForm(request.POST or None)
    if form.is_valid():
        form.instance.user = request.user
        instance = form.save()
        instance.save()
        return HttpResponseRedirect(reverse_lazy('jobs:employer-dashboard'))
    context = {
        'form': form,

    }
    return render(request,template_name, {'form': form})
'''

templates/jobs/employer/all-applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">All applicants who applied for your positions</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4>{{ applicant.user.get_full_name }}</h4>
                            <p><strong>Applied position: {{ applicant.job.title }}</strong></p>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Contact
                            </a>
                            <a href="{% url 'jobs:employee-details' applicant.user.pk %}"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Show Cv
                            </a>

                            <p>
                                <span class="badge badge-info">Applied {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                    <h3>No Applicants</h3>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/applicants.html
{% extends 'base.html' %}
{% block title %}
    Applicants
{% endblock %}
{% load static %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Applicants for the <span class="accent">{{ job.title }}</span> position</h1>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                {% for applicant in applicants %}
                    <div class="col-lg-6">
                        <div class="box applicant">
                            <h4>{{ applicant.user.get_full_name }}</h4>
                            <a href="#" data-toggle="modal" data-target="#contact-modal"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Contact
                            </a>

                            <a href="{% url 'jobs:employee-details' applicant.user.pk %}"
                               class="btn btn-outline-white-secondary btn-sm">
                                <i class="fa fa-envelope"></i>Show Cv
                            </a>

                            <p>
                                <span class="badge badge-info">Applied {{ applicant.created_at.astimezone }}</span>
                            </p>
                            <div class="d-flex justify-content-between">
                                <p class="intro"></p>
                                <div class="image">
                                    <img src="{% static 'img/avatar.png' %}" alt=""
                                         class="img-fluid rounded-circle">
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-md-12">
                            <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                                <ul class="pagination">
                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.previous_page_number }}"
                                               class="page-link">&laquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&laquo;</a>
                                        </li>
                                    {% endif %}
                                    {% for i in page_obj.paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item active">
                                                <a class="page-link">{{ i }}</a>
                                            </li>
                                        {% else %}
                                            <li class="page-item">
                                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                            </li>
                                        {% endif %}
                                    {% endfor %}
                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a href="?page={{ page_obj.next_page_number }}"
                                               class="page-link">&raquo;</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item disabled">
                                            <a class="page-link">&raquo;</a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </nav>
                        </div>
                    </div>
                {% else %}
                    <h3>No Applicants Applied For This Job</h3>
                {% endif %}
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Dashboard
{% endblock %}

{% block content %}

    <section class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h1 class="heading">Dashboard</h1>
                    <p class="lead text-center">All created jobs</p>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-right mb-5">
                    <a href="{% url 'jobs:employer-jobs-create' %}" class="btn btn-outline-white-primary">
                        <i class="fa fa-plus"></i>Add new position
                    </a>
                </div>
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-client-dashboard">
                            <thead>
                            <tr>
                                <th>Job title</th>
                                <th>Position filled</th>
                                <th>Date posted</th>
                                <th>Date expiring</th>
                                <th>Applicants</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for job in jobs %}

                                <tr>
                                    <th><a href="{% url 'jobs:jobs-detail' job.id %}">{{ job.title }}</a>
                                    </th>
                                    <td>
                                        {% if job.filled %}
                                            <span class="badge badge-success">Filled</span>
                                        {% else %}
                                            <span class="badge badge-secondary">Not Filled</span>
                                        {% endif %}
                                    </td>
                                    <td>{{ job.created_at }}</td>
                                    <td>{{ job.last_date }}</td>
                                    <td>
                                        <a href="{% url 'jobs:employer-dashboard-applicants' job.id %}"
                                           class="btn btn-success">
                                            <i class="fa fa-users"></i>{{ job.applicants.count }}
                                            <span class="hidden-xs hidden-sm">Applicants</span>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'jobs:job-details-update' job.pk %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-edit"></i>Edit
                                        </a>
                                        <br>
                                        {% if job.filled %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Filled</span>
                                            </a><br>
                                        {% else %}
                                            <a href="{% url 'jobs:job-mark-filled' job.id %}"
                                               class="btn btn-outline-white-secondary">
                                                <i class="fa fa-check-circle-o"></i>
                                                <span class="hidden-xs hidden-sm">Mark as </span>filled
                                            </a><br>
                                        {% endif %}
                                        <a href="{% url 'jobs:job-details-delete' job.pk %}" class="btn btn-outline-white-secondary">
                                            <i class="fa fa-times-circle-o"></i>Delete
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="pages">
                        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-4 mb-4">
                            <ul class="pagination">
                                <li class="page-item"><a href="#" aria-label="Previous" class="page-link"><span
                                        aria-hidden="true">«</span><span class="sr-only">Previous</span></a></li>
                                <li class="page-item active"><a href="#" class="page-link">1</a></li>
                                <li class="page-item"><a href="#" class="page-link">2</a></li>
                                <li class="page-item"><a href="#" class="page-link">3</a></li>
                                <li class="page-item"><a href="#" class="page-link">4</a></li>
                                <li class="page-item"><a href="#" aria-label="Next" class="page-link"><span
                                        aria-hidden="true">»</span><span class="sr-only">Next</span></a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/jobs/employer/delete_job.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Delete Job Post
{% endblock %}


{% block content %}
    <div class="col-lg-6 offset-3">
        <div class="box">
            <h3 class="heading">Delete Job Post</h3>
            <!-- start of first if -->

            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger alert-dismissable">
                            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}

                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger alert-dismissable">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <!-- start of first if -->

            <form action="" method="post">
                {% csrf_token %}

                <div class="row">
                            <div class="col-lg-12">
                               <!-- <h4>Job details</h4> -->
                                <p class="h5" style="color:red" > Are you sure you want to Delete the post of  "{{object.title}}"? </p>

                                <hr>
                            </div>
                </div>


                <div class="text-center">
                    <button type="submit" class="btn btn-outline-white-primary">
                        <i class="fa fa-signing"></i> Confirm
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}